### ISSUE TITLE
Handle default params

### ISSUE THREAD

**Issue by sixFingers** [sixFingers/streamex#7]
@desmondhume How would you handle default parameters? Currently doing it like [this](https://github.com/sixFingers/streamex/blob/master/lib/streamex/feed.ex#L102)

**Comment by desmondhume** [comment]
@sixFingers I don't think you need to define default parameters for that kind of value. 
Stream api already falls back on those values on its side, so you can omit them. I'd rather go for a simple keyword list passed by the user. 
Also, I wouldn't manipulate the passed in opts list. If I was passing in a `nil` value and the api was not supposed to handle `nil` value options, I'd rather see my program crash and fix my call's arguments than having the client obfuscate the call.

**Comment by sixFingers** [comment]
I agree. Feels like over-engineering. As for the `nil`, it's actually the main motivation for my question. Should i ensure that no `nil` value touches the remote API? Like i'm doing, by filtering values that are `nil`? But i guess that a developer willing to pass `nil` really wants to see the world explode. So yes, i would remove any code related to this, and let eventual errors from the API be handled with exceptions (i have to add them anyway to wrap common GetStream errors).
